#pragma once
#include "immvision/image.h"

#include <string>
#include <opencv2/core.hpp>

namespace ImmVision
{
    // <autogen:tostring_decl> // Autogenerated code below! Do not edit!

    std::string ToString(const ColormapScaleFromStatsData& params);
    std::string ToString(const ColormapSettingsData& params);
    std::string ToString(const MouseInformation& params);
    std::string ToString(const ImageParams& params);

    // </autogen:tostring_decl> // Autogenerated code end
};