#include "immvision/internal/misc/immvision_to_string.h"
#include "immvision/internal/misc/string_utils.h"

namespace ImmVision
{
    std::string ToString(const ColorAdjustmentsValues& params)
    {
        return "ColorAdjustmentsValues";
    }


    std::string ToString(const ImageNavigatorParams& v)
    {
        // <autogen:ImageNavigatorParams.ToString> // Autogenerated code below! Do not edit!
        // </autogen:ImageNavigatorParams.ToString> // Autogenerated code below! Do not edit!
    }

}
