#!/usr/bin/env python3
import sys
import os
import shutil
import subprocess

# Post build: deploy library to ${CMAKE_BINARY_DIR}/_pybind/,
# so that we can use it as a python package name immvision

if len(sys.argv) != 4:
    print("This script is intended to be called from cmake!")
    exit(1)


def run(cmd):
    print(cmd)
    subprocess.check_call(cmd, shell=True)


def do_symlink(src, dst):
    if os.name == "nt":
        print(f"copying {src} to {dst}")
        shutil.copy(src, dst)
    else:
        if os.path.islink(dst) or os.path.isfile(dst):
            os.remove(dst)
        run(f"ln -s {src} {dst}")


def write_text_file(filename, content):
    with open(filename, "w") as f:
        f.write(content)


def symlink_all_files_of_extension(immvision_pybind_source_dir, extension, dst_dir):
    for filename in os.listdir(immvision_pybind_source_dir):
        full_path = f"{immvision_pybind_source_dir}/{filename}"
        if os.path.isfile(full_path) and full_path.endswith(extension):
            do_symlink(full_path, f"{dst_dir}/{filename}")


immvision_pybind_source_dir = sys.argv[1]
current_bin_dir = sys.argv[2]
bin_dir = sys.argv[3]
# print(f"{immvision_pybind_source_dir=}")
# print(f"{current_bin_dir=}")
# print(f"{bin_dir=}")

pybind_libs_path = f"{bin_dir}/_pybind_libs"
out_dir = f"{pybind_libs_path}/immvision"
if not os.path.isdir(out_dir):
    os.makedirs(out_dir)


symlink_all_files_of_extension(current_bin_dir, "so", out_dir)
symlink_all_files_of_extension(current_bin_dir, "pyd", out_dir)
symlink_all_files_of_extension(f"{immvision_pybind_source_dir}/src/immvision", "py", out_dir)

# generate autogenerated files _pybind_libs_path.py
python_code_libs_path = f"""
# Autogenerated file

# This script makes it possible to run the examples without pip install
# It adds a path to sys.path where the compilation occured ({pybind_libs_path})
# if you run your script with `-dev` as a first argument 

import sys
if len(sys.argv) >= 2 and sys.argv[1] == "-dev":
    pybind_libs_path="{pybind_libs_path}"
    sys.path = [ pybind_libs_path ] + sys.path
"""

print(f"{sys.argv[0]}: generate autogenerated files _pybind_libs_path.py")
write_text_file(f"{immvision_pybind_source_dir}/debug_helper/_pybind_libs_path.py", python_code_libs_path)
write_text_file(f"{immvision_pybind_source_dir}/examples/_pybind_libs_path.py", python_code_libs_path)
