#!/usr/bin/env python3
import sys
import os
import shutil
import subprocess

# cmake will call this with 4 arguments:
# ${CMAKE_CURRENT_SOURCE_DIR} ${CMAKE_CURRENT_BINARY_DIR} ${CMAKE_BINARY_DIR} COMMAND

# Post build: deploy library to ${CMAKE_BINARY_DIR}/_pybind/,
# so that we can use it as a python package name immvision


if len(sys.argv) != 5:
    print("This script is intended to be called from cmake!")
    exit(1)

CMAKE_CURRENT_SOURCE_DIR = sys.argv[1]
CMAKE_CURRENT_BINARY_DIR = sys.argv[2]
CMAKE_BINARY_DIR = sys.argv[3]
COMMAND = sys.argv[4]

THIS_DIR = os.path.dirname(__file__)

VENV_PARENT_DIR = THIS_DIR
IS_DOCKER_BUILDER = os.path.isfile("/IMMVISION_DOCKER_BUILDER")
VENV_NAME = "venv" if not IS_DOCKER_BUILDER else "venv_docker"
VENV_DIR = f"{VENV_PARENT_DIR}/{VENV_NAME}"
# use "source" for bash, but for docker we may get "sh" which uses "." instead
SOURCE_PYBIND_VENV = f". {VENV_DIR}/bin/activate && " if not IS_DOCKER_BUILDER else f".  {VENV_DIR}/bin/activate && "

SILENT = True


# print(f"{immvision_pybind_source_dir=}")
# print(f"{current_bin_dir=}")
# print(f"{bin_dir=}")

def main():
    if COMMAND == "post_build_deploy":
        post_build_deploy()
    else:
        raise Exception("Bad command \n" + s)
        exit(1)


def run(cmd):
    if not SILENT:
        print(cmd)
    subprocess.check_call(cmd, shell=True)


def do_symlink(src, dst):
    if os.name == "nt":
        print(f"copying {src} to {dst}")
        shutil.copy(src, dst)
    else:
        if os.path.islink(dst) or os.path.isfile(dst):
            os.remove(dst)
        run(f"ln -s {src} {dst}")


def write_text_file(filename, content):
    with open(filename, "w") as f:
        f.write(content)


def symlink_all_files_of_extension(immvision_pybind_source_dir, extension, dst_dir):
    for filename in os.listdir(immvision_pybind_source_dir):
        full_path = f"{immvision_pybind_source_dir}/{filename}"
        if os.path.isfile(full_path) and full_path.endswith(extension):
            do_symlink(full_path, f"{dst_dir}/{filename}")



def post_build_deploy():
    pybind_libs_path = f"{CMAKE_BINARY_DIR}/_pybind_libs"
    out_dir = f"{pybind_libs_path}/immvision"
    if not os.path.isdir(out_dir):
        os.makedirs(out_dir)


    symlink_all_files_of_extension(CMAKE_CURRENT_BINARY_DIR, "so", out_dir)
    symlink_all_files_of_extension(CMAKE_CURRENT_BINARY_DIR, "pyd", out_dir)
    symlink_all_files_of_extension(f"{CMAKE_CURRENT_SOURCE_DIR}/src/immvision", "py", out_dir)

    # generate autogenerated files _pybind_libs_path.py
    python_code_libs_path = f"""
# Autogenerated file

# This script makes it possible to run the examples without pip install
# It adds a path to sys.path where the compilation occured ({pybind_libs_path})
# if you run your script with `-dev` as a first argument 

import sys
if len(sys.argv) >= 2 and sys.argv[1] == "-dev":
    pybind_libs_path="{pybind_libs_path}"
    sys.path = [ pybind_libs_path ] + sys.path
    """

    print(f"{sys.argv[0]}: generate autogenerated files _pybind_libs_path.py")
    write_text_file(f"{CMAKE_CURRENT_SOURCE_DIR}/debug_helper/_pybind_libs_path.py", python_code_libs_path)
    write_text_file(f"{CMAKE_CURRENT_SOURCE_DIR}/examples/_pybind_libs_path.py", python_code_libs_path)


if __name__ == "__main__":
    main()
